/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 17:47:54 GMT 2023
 */

package org.example.Fornecedor;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Fornecedor.FornecedorComNomeJaExistenteException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FornecedorComNomeJaExistenteException_ESTest extends FornecedorComNomeJaExistenteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FornecedorComNomeJaExistenteException fornecedorComNomeJaExistenteException0 = new FornecedorComNomeJaExistenteException("ConflictMarker.analyzeTime");
  }
}
