/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:56:58 GMT 2023
 */

package org.example.CasaInteligente;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.CasaInteligente.CasaInteligente;
import org.example.SmartDevice.SmartBulb;
import org.example.SmartDevice.SmartCamera;
import org.example.SmartDevice.SmartDevice;
import org.example.SmartDevice.SmartSpeaker;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CasaInteligente_ESTest extends CasaInteligente_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("LJ", (-32), "LJ");
      CasaInteligente casaInteligente1 = new CasaInteligente("LJ", (-2591), "LJ");
      boolean boolean0 = casaInteligente0.equals(casaInteligente1);
      assertEquals((-2591), casaInteligente1.getNIF());
      assertFalse(casaInteligente1.equals((Object)casaInteligente0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("5", 1028, "5");
      SmartSpeaker smartSpeaker0 = new SmartSpeaker((String) null);
      casaInteligente0.addDevice(smartSpeaker0);
      casaInteligente0.setAllOn(true);
      double double0 = casaInteligente0.getNrHorasDispositivoson();
      assertEquals(1028, casaInteligente0.getNIF());
      assertEquals(0.0072, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      SmartBulb smartBulb0 = (SmartBulb)casaInteligente0.getDevice("H`");
      smartBulb0.setHeight((-3862));
      smartBulb0.setOn(true);
      casaInteligente0.addDevice(smartBulb0);
      casaInteligente0.getNrHorasDispositivoson();
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("5", 1028, "5");
      SmartSpeaker smartSpeaker0 = new SmartSpeaker((String) null);
      casaInteligente0.addDevice(smartSpeaker0);
      casaInteligente0.getNrDispositivos();
      assertEquals(1028, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente((String) null, (-1), ", NIF = '");
      String string0 = casaInteligente0.getNome_proprietario();
      assertNull(string0);
      assertEquals((-1), casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("5", 1028, "5");
      casaInteligente0.getNome_proprietario();
      assertEquals(1028, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente(", devices='", (-1431655764), "a%jY_)[aB{Ys!1,(");
      assertEquals("a%jY_)[aB{Ys!1,(", casaInteligente0.getNomeFornecedor());
      
      casaInteligente0.setNomeFornecedor((String) null);
      casaInteligente0.getNomeFornecedor();
      assertEquals((-1431655764), casaInteligente0.getNIF());
      assertEquals(", devices='", casaInteligente0.getNome_proprietario());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("5", 1028, "5");
      casaInteligente0.getNomeFornecedor();
      assertEquals(1028, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("#F@v", 0, "");
      int int0 = casaInteligente0.getNIF();
      assertEquals("", casaInteligente0.getNomeFornecedor());
      assertEquals(0, int0);
      assertEquals("#F@v", casaInteligente0.getNome_proprietario());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("SmartBulb{", (-1166), "");
      int int0 = casaInteligente0.getNIF();
      assertEquals((-1166), int0);
      assertEquals("SmartBulb{", casaInteligente0.getNome_proprietario());
      assertEquals("", casaInteligente0.getNomeFornecedor());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      SmartDevice smartDevice0 = casaInteligente0.getDevice("H`");
      smartDevice0.setOn(true);
      casaInteligente0.addDevice(smartDevice0);
      SmartDevice smartDevice1 = casaInteligente0.getDevice("");
      assertTrue(smartDevice1.getOn());
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente(", devices='", (-1431655764), "a%jY_)[aB{Ys!1,(");
      casaInteligente0.setNIF(0);
      casaInteligente0.clone();
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("#F@v", 0, "");
      // Undeclared exception!
      try { 
        casaInteligente0.setLocations((Map<String, Set<String>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("i", 1, "i");
      // Undeclared exception!
      try { 
        casaInteligente0.setDevices((Map<String, SmartDevice>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      // Undeclared exception!
      try { 
        casaInteligente0.roomHasDevice("RBXem", "CasaInteligente{Nome Propriet\u00E1rio='', NIF = '0', Fornecedor = '', devices='{}', locations='{:Yx%@J1bK=[]}'}\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      HashMap<String, SmartDevice> hashMap0 = casaInteligente0.getDevices();
      SmartCamera smartCamera0 = new SmartCamera();
      hashMap0.put("3|5cmBrt9.9d;d>+WaR", smartCamera0);
      casaInteligente0.setDevices(hashMap0);
      casaInteligente0.setDeviceOn("");
      // Undeclared exception!
      try { 
        casaInteligente0.getNrHorasDispositivoson();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente((String) null, (-595), "");
      CasaInteligente casaInteligente1 = new CasaInteligente((String) null, 2, ", locations='");
      // Undeclared exception!
      try { 
        casaInteligente0.equals(casaInteligente1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("", 0, "?.i");
      // Undeclared exception!
      try { 
        casaInteligente0.addDevice((SmartDevice) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      CasaInteligente casaInteligente0 = null;
      try {
        casaInteligente0 = new CasaInteligente((CasaInteligente) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("5", 1028, "5");
      casaInteligente0.hasRoom(":s%D_:h$e");
      assertEquals(1028, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.addRoom("F/lhp;:+Z9i");
      boolean boolean0 = casaInteligente0.hasRoom("F/lhp;:+Z9i");
      assertTrue(boolean0);
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("\".oG?gtO+(TltMz", 2089, "\".oG?gtO+(TltMz");
      HashMap<String, Set<String>> hashMap0 = casaInteligente0.getLocations();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      hashMap0.put("~D!yZA'3}m", linkedHashSet0);
      casaInteligente0.setLocations(hashMap0);
      HashMap<String, Set<String>> hashMap1 = casaInteligente0.getLocations();
      assertEquals(2089, casaInteligente0.getNIF());
      assertEquals(1, hashMap1.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      SmartDevice smartDevice0 = casaInteligente0.getDevice("H`");
      casaInteligente0.addDevice(smartDevice0);
      casaInteligente0.getDevices();
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.getNomeFornecedor();
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      CasaInteligente casaInteligente1 = new CasaInteligente(casaInteligente0);
      assertTrue(casaInteligente1.equals((Object)casaInteligente0));
      
      casaInteligente0.addRoom("#rewJ{@fn");
      boolean boolean0 = casaInteligente1.equals(casaInteligente0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("SmartCamera{", 39, "SmartCamera{");
      CasaInteligente casaInteligente1 = casaInteligente0.clone();
      assertTrue(casaInteligente1.equals((Object)casaInteligente0));
      
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      casaInteligente1.addDevice(smartSpeaker0);
      boolean boolean0 = casaInteligente0.equals(casaInteligente1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.setNomeFornecedor("(");
      CasaInteligente casaInteligente1 = new CasaInteligente();
      boolean boolean0 = casaInteligente0.equals(casaInteligente1);
      assertFalse(boolean0);
      assertEquals(0, casaInteligente1.getNIF());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      CasaInteligente casaInteligente1 = new CasaInteligente();
      casaInteligente1.setNIF(20);
      boolean boolean0 = casaInteligente0.equals(casaInteligente1);
      assertEquals(20, casaInteligente1.getNIF());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      CasaInteligente casaInteligente1 = new CasaInteligente("'", 18, "(");
      boolean boolean0 = casaInteligente0.equals(casaInteligente1);
      assertEquals(0, casaInteligente0.getNIF());
      assertEquals("(", casaInteligente1.getNomeFornecedor());
      assertFalse(boolean0);
      assertEquals("'", casaInteligente1.getNome_proprietario());
      assertEquals(18, casaInteligente1.getNIF());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      CasaInteligente casaInteligente1 = new CasaInteligente(casaInteligente0);
      boolean boolean0 = casaInteligente1.equals(casaInteligente0);
      assertEquals(0, casaInteligente0.getNIF());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      boolean boolean0 = casaInteligente0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente((String) null, (-595), "");
      boolean boolean0 = casaInteligente0.equals(casaInteligente0);
      assertTrue(boolean0);
      assertEquals((-595), casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      boolean boolean0 = casaInteligente0.equals("Xb");
      assertEquals("~ubbXl", casaInteligente0.getNome_proprietario());
      assertEquals("WHB`?`r_", casaInteligente0.getNomeFornecedor());
      assertFalse(boolean0);
      assertEquals((-32), casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.addRoom("");
      casaInteligente0.addToRoom("", "");
      boolean boolean0 = casaInteligente0.roomHasDevice("", "");
      assertTrue(boolean0);
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.addRoom("");
      boolean boolean0 = casaInteligente0.roomHasDevice("", "");
      assertFalse(boolean0);
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.addRoom("!w.");
      try { 
        casaInteligente0.addRoom("!w.");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Esta Divis\u00E3o j\u00E1 existe!
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      HashMap<String, SmartDevice> hashMap0 = casaInteligente0.getDevices();
      SmartBulb smartBulb0 = new SmartBulb("Xb");
      hashMap0.put("WHB`?`r_", smartBulb0);
      casaInteligente0.setDevices(hashMap0);
      casaInteligente0.setOn("Xb", true);
      assertEquals("WHB`?`r_", casaInteligente0.getNomeFornecedor());
      assertEquals("~ubbXl", casaInteligente0.getNome_proprietario());
      assertEquals((-32), casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente((String) null, (-1), ", NIF = '");
      casaInteligente0.setOn("!w.", false);
      assertEquals((-1), casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      SmartCamera smartCamera0 = new SmartCamera();
      casaInteligente0.addDevice(smartCamera0);
      boolean boolean0 = casaInteligente0.existsDevice("");
      assertTrue(boolean0);
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente(", devices='", (-1431655764), "a%jY_)[aB{Ys!1,(");
      boolean boolean0 = casaInteligente0.existsDevice(", Fornecedor = '");
      assertEquals((-1431655764), casaInteligente0.getNIF());
      assertEquals("a%jY_)[aB{Ys!1,(", casaInteligente0.getNomeFornecedor());
      assertEquals(", devices='", casaInteligente0.getNome_proprietario());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      HashMap<String, SmartDevice> hashMap0 = casaInteligente0.getDevices();
      SmartCamera smartCamera0 = new SmartCamera();
      hashMap0.put("3|5cmBrt9.9d;d>+WaR", smartCamera0);
      casaInteligente0.setDevices(hashMap0);
      CasaInteligente casaInteligente1 = casaInteligente0.clone();
      assertEquals("~ubbXl", casaInteligente1.getNome_proprietario());
      assertEquals((-32), casaInteligente1.getNIF());
      assertEquals("WHB`?`r_", casaInteligente1.getNomeFornecedor());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente(", devices='", 1, "-");
      // Undeclared exception!
      try { 
        casaInteligente0.addToRoom("", "-");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      casaInteligente0.getNome_proprietario();
      assertEquals(0, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("SmartCamera{", 39, "SmartCamera{");
      int int0 = casaInteligente0.getNIF();
      assertEquals(39, int0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      // Undeclared exception!
      try { 
        casaInteligente0.setDeviceOn("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.CasaInteligente.CasaInteligente", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente();
      String string0 = casaInteligente0.toString();
      assertEquals("CasaInteligente{Nome Propriet\u00E1rio='', NIF = '0', Fornecedor = '', devices='{}', locations='{}'}\n", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("SmartCamera{", 39, "SmartCamera{");
      casaInteligente0.setNome_proprietario("SmartCamera{");
      assertEquals(39, casaInteligente0.getNIF());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      casaInteligente0.getNrHorasDispositivoson();
      assertEquals((-32), casaInteligente0.getNIF());
      assertEquals("~ubbXl", casaInteligente0.getNome_proprietario());
      assertEquals("WHB`?`r_", casaInteligente0.getNomeFornecedor());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      CasaInteligente casaInteligente0 = new CasaInteligente("~ubbXl", (-32), "WHB`?`r_");
      casaInteligente0.getNrDispositivos();
      assertEquals((-32), casaInteligente0.getNIF());
      assertEquals("~ubbXl", casaInteligente0.getNome_proprietario());
      assertEquals("WHB`?`r_", casaInteligente0.getNomeFornecedor());
  }
}
