/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:55:38 GMT 2023
 */

package org.example.SmartDevice;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.SmartDevice.SmartBulb;
import org.example.SmartDevice.SmartCamera;
import org.example.SmartDevice.SmartDevice;
import org.example.SmartDevice.SmartSpeaker;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartDevice_ESTest extends SmartDevice_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("-1M<6L");
      String string0 = smartBulb0.toString();
      assertEquals("SmartBulb{id='-1M<6L', on='false', tone='1', height='0.0'}", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      smartSpeaker0.turnOn();
      boolean boolean0 = smartSpeaker0.getOn();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker((String) null, 0, "E)7w'Rfwf+<Y'8", "");
      String string0 = smartSpeaker0.getID();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      String string0 = smartSpeaker0.getID();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("\"");
      double double0 = smartSpeaker0.getConsume();
      assertEquals(0.0072, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("'8e?h.q{", (-1071), (-1071));
      double double0 = smartBulb0.getConsume();
      assertEquals((-26.455000000000002), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      boolean boolean0 = smartSpeaker0.equals(smartSpeaker0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("4wZ1V,_N", 2595, "-1M<6L", "-1M<6L");
      boolean boolean0 = smartSpeaker0.equals("-1M<6L");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      smartSpeaker0.turnOn();
      smartSpeaker0.clone();
      assertTrue(smartSpeaker0.getOn());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      SmartDevice smartDevice0 = smartSpeaker0.clone();
      assertFalse(smartDevice0.getOn());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera();
      // Undeclared exception!
      try { 
        smartCamera0.getConsume();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera(", height='", (String) null, 2);
      // Undeclared exception!
      try { 
        smartCamera0.getConsume();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.SmartDevice.SmartCamera", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera("8", "8", 0);
      // Undeclared exception!
      try { 
        smartCamera0.getConsume();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.example.SmartDevice.SmartCamera", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker((String) null);
      SmartSpeaker smartSpeaker1 = new SmartSpeaker((String) null);
      // Undeclared exception!
      try { 
        smartSpeaker0.equals(smartSpeaker1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker("dr.25", 2, "dr.25", "dr.25");
      String string0 = smartSpeaker0.getID();
      assertEquals("dr.25", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      boolean boolean0 = smartSpeaker0.getOn();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      smartSpeaker0.turnOn();
      SmartSpeaker smartSpeaker1 = new SmartSpeaker("SmartSpeaker {id='', on='true', volume='0', channel='', brand=''}", 20, "SmartSpeaker {id='', on='true', volume='0', channel='', brand=''}", "SmartSpeaker {id='', on='true', volume='0', channel='', brand=''}");
      smartSpeaker0.equals(smartSpeaker1);
      assertTrue(smartSpeaker0.getOn());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      SmartSpeaker smartSpeaker1 = new SmartSpeaker(smartSpeaker0);
      boolean boolean0 = smartSpeaker1.equals(smartSpeaker0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartSpeaker smartSpeaker0 = new SmartSpeaker();
      SmartSpeaker smartSpeaker1 = new SmartSpeaker("SmartSpeaker {id='', on='true', volume='0', channel='', brand=''}", 20, "SmartSpeaker {id='', on='true', volume='0', channel='', brand=''}", "SmartSpeaker {id='', on='true', volume='0', channel='', brand=''}");
      boolean boolean0 = smartSpeaker0.equals(smartSpeaker1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera(", height='", (String) null, 2);
      smartCamera0.setOn(false);
      assertFalse(smartCamera0.getOn());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartCamera smartCamera0 = new SmartCamera();
      smartCamera0.turnOff();
      assertFalse(smartCamera0.getOn());
  }
}
