/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:54:56 GMT 2023
 */

package org.example.Fornecedor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Fatura.Fatura;
import org.example.Fornecedor.Fornecedor;
import org.example.Fornecedor.FornecedorTipo1;
import org.example.Fornecedor.FornecedorTipo2;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FornecedorTipo1_ESTest extends FornecedorTipo1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1();
      double double0 = fornecedorTipo1_0.precoDiaPorDispositivo(10, 10);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1((String) null, (-488.2910351), (-488.2910351), 189.56926875);
      double double0 = fornecedorTipo1_0.precoDiaPorDispositivo(0, 0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1("", 331.97071, 331.97071, 1.0);
      double double0 = fornecedorTipo1_0.precoDiaPorDispositivo((-3902), 331.97071);
      assertEquals(298.773639, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1("Eu_|x6!qm", (-1612.0686850064), (-1612.0686850064), (-1612.0686850064));
      double double0 = fornecedorTipo1_0.precoDiaPorDispositivo(2224, 0.1);
      assertEquals((-161.20686850064), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1("", 1.0, (-3037.1454), (-3037.1454));
      Fornecedor fornecedor0 = fornecedorTipo1_0.clone();
      assertEquals((-3037.1454), fornecedor0.getMultiplicador(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1((String) null, (-488.2910351), (-488.2910351), 189.56926875);
      Fornecedor fornecedor0 = fornecedorTipo1_0.clone();
      assertEquals((-488.2910351), fornecedor0.getImposto(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1("kq", (-769.3), 1969.990336579392, 0.0);
      Fornecedor fornecedor0 = fornecedorTipo1_0.clone();
      assertTrue(fornecedor0.equals((Object)fornecedorTipo1_0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FornecedorTipo2 fornecedorTipo2_0 = new FornecedorTipo2("6F):(Y", (-4674.69), (-603.400685), 1264.5111);
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1(fornecedorTipo2_0);
      assertEquals((-4674.69), fornecedorTipo1_0.getPrecoBase(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = new FornecedorTipo1();
      Fornecedor fornecedor0 = fornecedorTipo1_0.clone();
      assertTrue(fornecedor0.equals((Object)fornecedorTipo1_0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FornecedorTipo1 fornecedorTipo1_0 = null;
      try {
        fornecedorTipo1_0 = new FornecedorTipo1((Fornecedor) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Fornecedor.Fornecedor", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMap<Integer, List<Fatura>> hashMap0 = new HashMap<Integer, List<Fatura>>();
      FornecedorTipo1 fornecedorTipo1_0 = null;
      try {
        fornecedorTipo1_0 = new FornecedorTipo1("oVg.example.Fornecdor^FornecedoTipo1", 2.5931137881981576, 2.5931137881981576, 2.5931137881981576, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Fornecedor.Fornecedor", e);
      }
  }
}
