/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:55:42 GMT 2023
 */

package org.example.CasaInteligente;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.CasaInteligente.DivisaoJaExisteException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DivisaoJaExisteException_ESTest extends DivisaoJaExisteException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DivisaoJaExisteException divisaoJaExisteException0 = new DivisaoJaExisteException("yZVe ");
  }
}
