/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:55:00 GMT 2023
 */

package org.example.Main;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.Main.CasaExceptionFornecedorNaoExiste;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CasaExceptionFornecedorNaoExiste_ESTest extends CasaExceptionFornecedorNaoExiste_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CasaExceptionFornecedorNaoExiste casaExceptionFornecedorNaoExiste0 = new CasaExceptionFornecedorNaoExiste(" s4tO2np^Q%lj>oz n");
  }
}
