/*
 * This file was automatically generated by EvoSuite
 * Thu May 04 15:55:56 GMT 2023
 */

package org.example.SmartDevice;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.SmartDevice.SmartBulb;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartBulb_ESTest extends SmartBulb_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(":Ssw^]z)(Q26Qe]_W@", 2, 0.0);
      SmartBulb smartBulb1 = smartBulb0.clone();
      smartBulb0.setHeight(0.36);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(0.36, smartBulb0.getHeight(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb(", on='", 164, 164);
      SmartBulb smartBulb1 = new SmartBulb(", on='", (-114), 1425.283227);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals((-114), smartBulb1.getTone());
      assertEquals(1425.283227, smartBulb1.getHeight(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      smartBulb0.setTone(2);
      assertEquals(2, smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
      
      smartBulb0.setTone((-40));
      int int0 = smartBulb0.getTone();
      assertEquals(0.32, smartBulb0.getConsume(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("@3N,VrC/H", (-1), (-1));
      int int0 = smartBulb0.getTone();
      assertEquals((-1), int0);
      assertEquals((-1.0), smartBulb0.getHeight(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, 800, 800);
      double double0 = smartBulb0.getHeight();
      assertEquals(800.0, double0, 0.01);
      assertEquals(20.32, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("v", (-565), (-565));
      double double0 = smartBulb0.getHeight();
      assertEquals((-565.0), double0, 0.01);
      assertEquals((-13.805), smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("~J=\"#6k<O-", (-72), (-72));
      assertEquals((-72), smartBulb0.getTone());
      
      smartBulb0.setTone(490);
      double double0 = smartBulb0.getConsume();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", (-1744), (-1744));
      double double0 = smartBulb0.getConsume();
      assertEquals((-43.28), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      smartBulb0.turnOn();
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals(0.34, smartBulb1.getConsume(), 0.01);
      assertEquals(0.0, smartBulb1.getHeight(), 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("~J=\"#6k<O-", (-72), (-72));
      assertEquals((-1.48), smartBulb0.getConsume(), 0.01);
      
      smartBulb0.setTone(490);
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertTrue(smartBulb1.equals((Object)smartBulb0));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("~J=\"#6k<O-", (-72), (-72));
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals((-1.48), smartBulb1.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartBulb smartBulb0 = null;
      try {
        smartBulb0 = new SmartBulb((SmartBulb) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.SmartDevice.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb1.setHeight(2);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(2.0, smartBulb1.getHeight(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb0.setTone(0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(0.32, smartBulb0.getConsume(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(0.0, smartBulb1.getHeight(), 0.01);
      assertTrue(boolean0);
      assertEquals(1, smartBulb1.getTone());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      boolean boolean0 = smartBulb0.equals((Object) null);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      boolean boolean0 = smartBulb0.equals(smartBulb0);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      Object object0 = new Object();
      boolean boolean0 = smartBulb0.equals(object0);
      assertFalse(boolean0);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
      
      smartBulb0.setTone((-40));
      smartBulb0.clone();
      assertEquals(0.32, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = smartBulb0.getHeight();
      assertEquals(0.0, double0, 0.01);
      assertEquals(1, smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("SmartBu#b{");
      double double0 = smartBulb0.getConsume();
      assertEquals(0.34, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      int int0 = smartBulb0.getTone();
      assertEquals(1, int0);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, 800, 800);
      SmartBulb smartBulb1 = smartBulb0.clone();
      // Undeclared exception!
      try { 
        smartBulb1.equals(smartBulb0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.SmartDevice.SmartDevice", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, 800, 800);
      String string0 = smartBulb0.toString();
      assertEquals("SmartBulb{id='null', on='false', tone='800', height='800.0'}", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("org.example.SmartDevice.martBRlb", 473, 473);
      SmartBulb smartBulb1 = new SmartBulb();
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(12.145000000000001, smartBulb0.getConsume(), 0.01);
      assertEquals(0.34, smartBulb1.getConsume(), 0.01);
      assertFalse(boolean0);
  }
}
