/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue May 16 17:47:45 GMT 2023
 */

package org.example.CasaInteligente;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CasaExceptionNifExistente_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.example.CasaInteligente.CasaExceptionNifExistente"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "/home/anightatheopera/Documents/ats2023/ats"); 
    java.lang.System.setProperty("user.home", "/home/anightatheopera"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "anightatheopera"); 
    java.lang.System.setProperty("user.timezone", "Europe/Lisbon"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CasaExceptionNifExistente_ESTest_scaffolding.class.getClassLoader() ,
      "org.example.CasaInteligente.CasaExceptionNifExistente"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CasaExceptionNifExistente_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.example.CasaInteligente.CasaExceptionNifExistente",
      "org.eclipse.aether.DefaultRepositorySystemSession",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullMirrorSelector",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullProxySelector",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullAuthenticationSelector",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullArtifactTypeRegistry",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullDependencyTraverser",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullDependencyManager",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullDependencySelector",
      "org.eclipse.aether.DefaultRepositorySystemSession$NullDependencyGraphTransformer",
      "org.eclipse.aether.DefaultSessionData",
      "org.eclipse.aether.util.repository.SimpleArtifactDescriptorPolicy",
      "org.eclipse.aether.util.repository.ChainedWorkspaceReader",
      "org.eclipse.aether.repository.LocalRepository",
      "org.eclipse.aether.artifact.AbstractArtifact",
      "org.eclipse.aether.artifact.DefaultArtifact",
      "org.eclipse.aether.util.graph.selector.OptionalDependencySelector",
      "org.eclipse.aether.DefaultRepositoryCache",
      "org.eclipse.aether.metadata.AbstractMetadata",
      "org.eclipse.aether.metadata.DefaultMetadata"
    );
  }
}
