/*
 * This file was automatically generated by EvoSuite
 * Tue May 16 16:02:28 GMT 2023
 */

package org.example.SmartDevice;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.example.SmartDevice.SmartBulb;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmartBulb_ESTest extends SmartBulb_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("tDPd", 0, (-465.0));
      String string0 = smartBulb0.toString();
      assertEquals("SmartBulb{id='tDPd', on='false', tone='0', height='-465.0'}", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      assertEquals(0.0, smartBulb1.getHeight(), 0.01);
      
      smartBulb1.setHeight((-1.0));
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("T?;__jCLCp", (-4848), (-1.0));
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals((-4848), smartBulb0.getTone());
      
      smartBulb0.setTone(0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("");
      boolean boolean0 = smartBulb0.equals(smartBulb0);
      assertTrue(boolean0);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", 39, (-220.0));
      assertEquals(0.0, smartBulb0.getConsume(), 0.01);
      
      smartBulb0.setTone(2152);
      assertEquals((-0.7400000000000001), smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("tDPd", 0, (-465.0));
      int int0 = smartBulb0.getTone();
      assertEquals((-465.0), smartBulb0.getHeight(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      int int0 = smartBulb0.getTone();
      assertEquals(1, int0);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", 0, 3882.70886087196);
      double double0 = smartBulb0.getHeight();
      assertEquals(3882.70886087196, double0, 0.01);
      assertEquals(19.7335443043598, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, 0, (-4572.6875898896205));
      double double0 = smartBulb0.getHeight();
      assertEquals((-22.5434379494481), smartBulb0.getConsume(), 0.01);
      assertEquals((-4572.6875898896205), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, (-778), (-778));
      double double0 = smartBulb0.getConsume();
      assertEquals((-19.13), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("tDPd", 0, (-465.0));
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals((-2.0050000000000003), smartBulb1.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      smartBulb0.turnOn();
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals(0.0, smartBulb1.getHeight(), 0.01);
      assertEquals(0.34, smartBulb1.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("", 39, (-220.0));
      SmartBulb smartBulb1 = smartBulb0.clone();
      assertEquals(0.0, smartBulb1.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SmartBulb smartBulb0 = null;
      try {
        smartBulb0 = new SmartBulb((SmartBulb) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.SmartDevice.SmartBulb", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null, (-778), (-778));
      int int0 = smartBulb0.getTone();
      assertEquals((-778), int0);
      assertEquals((-778.0), smartBulb0.getHeight(), 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = new SmartBulb(smartBulb0);
      smartBulb1.setHeight(2);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(2.0, smartBulb1.getHeight(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = smartBulb0.clone();
      smartBulb0.setTone(0);
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(0.32, smartBulb0.getConsume(), 0.01);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("i@u_;9Q[ww^L", 39, 39);
      boolean boolean0 = smartBulb0.equals("i@u_;9Q[ww^L");
      assertFalse(boolean0);
      assertEquals(1.2950000000000002, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      boolean boolean0 = smartBulb0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      SmartBulb smartBulb1 = new SmartBulb("SmartBulb{id='', on='false', tone='2', height='0.0'}");
      boolean boolean0 = smartBulb1.equals(smartBulb0);
      assertFalse(boolean0);
      assertEquals(0.34, smartBulb1.getConsume(), 0.01);
      assertEquals(0.34, smartBulb0.getConsume(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      smartBulb0.setTone(2);
      assertEquals(2, smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null);
      assertEquals(1, smartBulb0.getTone());
      
      smartBulb0.setTone((-728));
      assertEquals(0, smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = smartBulb0.getConsume();
      assertEquals(0.34, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb();
      double double0 = smartBulb0.getHeight();
      assertEquals(0.0, double0, 0.01);
      assertEquals(1, smartBulb0.getTone());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null);
      SmartBulb smartBulb1 = smartBulb0.clone();
      // Undeclared exception!
      try { 
        smartBulb0.equals(smartBulb1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.SmartDevice.SmartDevice", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb((String) null);
      String string0 = smartBulb0.toString();
      assertEquals("SmartBulb{id='null', on='false', tone='1', height='0.0'}", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SmartBulb smartBulb0 = new SmartBulb("i@u_;9Q[ww^L", 39, 39);
      SmartBulb smartBulb1 = smartBulb0.clone();
      boolean boolean0 = smartBulb0.equals(smartBulb1);
      assertEquals(39.0, smartBulb0.getHeight(), 0.01);
      assertEquals(39, smartBulb1.getTone());
      assertTrue(boolean0);
  }
}
